version: '2'
services:
  redis:
    container_name: slamby_redis
    image: redis:3.0-32bit
    restart: always
    cpu_shares: 512
    volumes:
      - /usr/share/redis/data:/data
  elasticsearch:
    container_name: slamby_elasticsearch
    restart: always
    image: slamby/elasticsearch:1.0
    mem_limit: 1024m
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_HEAP_SIZE: 256m
    oom_score_adj: -1000
    cpu_shares: 512
  slambyapi:
    container_name: slamby_api
    restart: always
    image: slamby/slamby.api:1.1.0
    environment:
      SlambyApi__ApiSecret: s3cr3t
    volumes:
      - /home/slamby:/Slamby
    depends_on:
      - elasticsearch
      - redis
    links:
      - elasticsearch
      - redis
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    oom_score_adj: -1000
    cpu_shares: 1024
  nginx:
    container_name: slamby_nginx
    image: slamby/nginx:1.0-wu
    restart: always
    ports:
      - "80:80"
    depends_on:
      - slambyapi
      - slambyapiupdater
    links:
      - slambyapi
      - slambyapiupdater
    cpu_shares: 512
  slambyapiupdater:
    container_name: slamby_api_updater
    image: slamby/slamby.api-updater:0.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cpu_shares: 512